# Generated by Django 3.0.5 on 2020-04-09 20:42

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musicApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicAppAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=25)),
                ('location', models.CharField(blank=True, max_length=25)),
                ('about', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, upload_to=account.models.user_directory_path)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('plan', models.PositiveIntegerField(choices=[(1, 'basic'), (2, 'prime')], default=1)),
                ('plan_expire', models.DateTimeField(blank=True, null=True)),
                ('setting_get_email', models.BooleanField(default=True)),
                ('setting_get_sms', models.BooleanField(default=False)),
                ('setting_normalize_volume', models.BooleanField(default=True)),
                ('setting_stream_quality', models.PositiveIntegerField(choices=[(320, '320kb'), (128, '128kb')], default=320)),
                ('setting_theme_night_mode', models.BooleanField(default=False)),
                ('favorite', models.ManyToManyField(blank=True, to='musicApp.Music')),
                ('history', models.ManyToManyField(blank=True, related_name='user_history', to='musicApp.Music')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
