# Generated by Django 3.0.4 on 2020-04-05 18:27

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musicApp', '0009_auto_20200326_1908'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicAppAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=25)),
                ('about', models.TextField()),
                ('avatar', models.ImageField(upload_to=account.models.user_directory_path)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('plan', models.PositiveIntegerField(choices=[(1, 'basic'), (2, 'prime')])),
                ('plan_expire', models.DateTimeField()),
                ('setting_get_email', models.BooleanField(default=True)),
                ('setting_get_sms', models.BooleanField(default=False)),
                ('setting_normalize_volume', models.BooleanField(default=True)),
                ('setting_stream_quality', models.PositiveIntegerField(choices=[(320, '320kb'), (128, '128kb')])),
                ('setting_theme_night_mode', models.BooleanField(default=False)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicApp.Music')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
