# Generated by Django 3.0.4 on 2020-03-16 14:15

from django.db import migrations, models
import django.db.models.deletion
import musicApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed', max_length=50)),
                ('pub_date', models.DateField(null=True)),
                ('cover', models.ImageField(upload_to=musicApp.models.album_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed', max_length=50)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('plays', models.PositiveIntegerField(default=0)),
                ('lyrics', models.TextField(null=True)),
                ('music', models.CharField(max_length=50, null=True)),
                ('song_writer', models.CharField(max_length=50, null=True)),
                ('arrangement', models.CharField(max_length=50, null=True)),
                ('mix_mastering', models.CharField(max_length=50, null=True)),
                ('cover_art', models.CharField(max_length=50, null=True)),
                ('song', models.FileField(upload_to=musicApp.models.music_directory_path)),
                ('cover', models.ImageField(upload_to=musicApp.models.music_directory_path)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicApp.Album')),
                ('genre', models.ManyToManyField(to='musicApp.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=50)),
                ('biography', models.TextField(null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('follows', models.PositiveIntegerField(default=0)),
                ('cover', models.ImageField(upload_to=musicApp.models.singer_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed', max_length=50)),
                ('cover', models.ImageField(upload_to=musicApp.models.playlist_directory_path)),
                ('songs', models.ManyToManyField(to='musicApp.Music')),
            ],
        ),
        migrations.AddField(
            model_name='music',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicApp.Singer'),
        ),
        migrations.AddField(
            model_name='album',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicApp.Singer'),
        ),
    ]
