# Generated by Django 3.0.5 on 2020-04-09 20:42

from django.db import migrations, models
import django.db.models.deletion
import musicApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed', max_length=50)),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, default='default_320_320', upload_to=musicApp.models.album_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed', max_length=50)),
                ('info', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('due_time', models.DateTimeField()),
                ('image', models.ImageField(blank=True, upload_to=musicApp.models.event_directory_path)),
                ('background_image', models.ImageField(upload_to=musicApp.models.event_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed', max_length=50)),
                ('cover', models.ImageField(blank=True, default='default_540_320.jpg', upload_to=musicApp.models.genre_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed', max_length=50)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('plays', models.PositiveIntegerField(default=0)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('music', models.CharField(blank=True, max_length=50, null=True)),
                ('song_writer', models.CharField(blank=True, max_length=50, null=True)),
                ('arrangement', models.CharField(blank=True, max_length=50, null=True)),
                ('mix_mastering', models.CharField(blank=True, max_length=50, null=True)),
                ('cover_art', models.CharField(blank=True, max_length=50, null=True)),
                ('top_chart', models.BooleanField(default=False)),
                ('premium', models.BooleanField(default=False)),
                ('song', models.FileField(upload_to=musicApp.models.music_directory_path)),
                ('cover', models.ImageField(blank=True, default='default_320_320', upload_to=musicApp.models.music_directory_path)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicApp.Album')),
                ('genre', models.ManyToManyField(to='musicApp.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=50)),
                ('biography', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('follows', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('cover', models.ImageField(blank=True, default='default_320_320', upload_to=musicApp.models.singer_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed', max_length=50)),
                ('cover', models.ImageField(blank=True, default='default_540_320', upload_to=musicApp.models.playlist_directory_path)),
                ('songs', models.ManyToManyField(to='musicApp.Music')),
            ],
        ),
        migrations.CreateModel(
            name='MusicPlay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datePlay', models.DateField()),
                ('plays', models.PositiveIntegerField(default=0)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicApp.Music')),
            ],
        ),
        migrations.AddField(
            model_name='music',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicApp.Singer'),
        ),
        migrations.AddField(
            model_name='album',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicApp.Singer'),
        ),
    ]
