# Generated by Django 3.0.4 on 2020-03-16 14:30

from django.db import migrations, models
import musicApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('musicApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, upload_to=musicApp.models.album_directory_path),
        ),
        migrations.AlterField(
            model_name='album',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='arrangement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='cover',
            field=models.ImageField(blank=True, upload_to=musicApp.models.music_directory_path),
        ),
        migrations.AlterField(
            model_name='music',
            name='cover_art',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='mix_mastering',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='music',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='song_writer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='cover',
            field=models.ImageField(blank=True, upload_to=musicApp.models.playlist_directory_path),
        ),
        migrations.AlterField(
            model_name='singer',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='singer',
            name='cover',
            field=models.ImageField(blank=True, upload_to=musicApp.models.singer_directory_path),
        ),
        migrations.AlterField(
            model_name='singer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
