# Generated by Django 3.0.4 on 2020-03-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicApp', '0002_auto_20200316_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='top_chart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='singer',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
