# Generated by Django 3.0.4 on 2020-03-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicApp', '0003_auto_20200318_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
