# Generated by Django 3.0.4 on 2020-03-22 15:36

from django.db import migrations, models
import musicApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('musicApp', '0004_music_premium'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed', max_length=50)),
                ('info', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(default='Unnamed', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('due_time', models.DateTimeField()),
                ('image', models.ImageField(blank=True, upload_to=musicApp.models.event_directory_path)),
                ('background_image', models.ImageField(blank=True, upload_to=musicApp.models.event_directory_path)),
            ],
        ),
    ]
