# Generated by Django 3.0.4 on 2020-03-26 14:33

from django.db import migrations, models
import musicApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('musicApp', '0007_musicplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='cover',
            field=models.ImageField(blank=True, default='default_540_320.jpg', upload_to=musicApp.models.genre_directory_path),
        ),
    ]
