# Generated by Django 3.0.4 on 2020-03-26 14:38

from django.db import migrations, models
import musicApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('musicApp', '0008_genre_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, default='default_320_320', upload_to=musicApp.models.album_directory_path),
        ),
        migrations.AlterField(
            model_name='event',
            name='background_image',
            field=models.ImageField(upload_to=musicApp.models.event_directory_path),
        ),
        migrations.AlterField(
            model_name='music',
            name='cover',
            field=models.ImageField(blank=True, default='default_320_320', upload_to=musicApp.models.music_directory_path),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='cover',
            field=models.ImageField(blank=True, default='default_540_320', upload_to=musicApp.models.playlist_directory_path),
        ),
        migrations.AlterField(
            model_name='singer',
            name='cover',
            field=models.ImageField(blank=True, default='default_320_320', upload_to=musicApp.models.singer_directory_path),
        ),
    ]
